### PR TITLE
h265nal: support for serialization of sei messages and payload states

### PR DESCRIPTION
**Pull request by jhnbwrs**
A few small changes:

- h265nal: add unit test for H265SeiUnknownParser
- h265nal: adjust indent level for the state payload
- h265nal: apply clang google style formatting fixes
- h265nal: support for serialization of sei messages and payload states
- h265nal: add serialization to sei state unit tests

### CODE REVIEW

**Comment by chemag** [comment]
I just cherry-picked the 2x minor patches (c95299d and b1f77ce)

**Comment by chemag** [comment]
Before we implement serialization, what is the use case? 

For the parser (and dumper), the goal is to allow humans reading the internals of h265 Annex B files. I use the tools/h265nal binary tool all the time to understand the fields inside an Annex B file. The tool uses the parser to convert the binary string into a struct/class, and then the dumper to write text lines (human-readable).

**Comment by chemag** [comment]
For me, the main use case is human-readable edit of h265 Annex B files. 

In the past, I have used a serializer alongside a parser to modify binary strings. For example, [m2pb](https://github.com/chemag/m2pb) uses this approach. The idea is to use the parser to convert the binary string to text, edit the text, and finally convert the text back to a binary string. We could use this e.g. to modify the colorimetry information in SPS NAL headers. The idea will be:

(1) h265nal in.265 in.265.txt
(2) modify in.265.txt at will
(3) h265nal --serialize in.265.txt out.265

You can even script the text edition (step 2). 

Now, this would require storing the printable structures using protobuf.

(1) Right now the parser works as follows:
```
+---------+  h265*::parse/dump  +---------+
|h265 bin |-------------------->|h265 text|
+---------+                     +---------+
```

We use `parse()` functions to convert to the State structs, and then the `dump()` functions to make the contents human-readable.

The issue with adding the reverse path is that we need (a) an h265 text parser that converts text into State structs (hard), and (b) an h265 binary dumper that packs State structs according to the standard.

(2) What we really want is to use protobuf text as the final format, and protobuf structs instead of our actual structs. The idea would be to implement this:
```
+---------+  h265*::parse   +-------------+ protobuf +---------+
|h265 bin |---------------->|h265 protobuf|<-------->|h265 text|
+---------+<--------------- +-------------+          +---------+
            h265*::serialize
```

By replacing the State structs with protobuf, we would get the fdump functions for free, and the h265 text parsing for free. Note that the current h265 text format is as close to protobuf as possible (we may have issues with the vectors -- I forgot what support does protobuf text have on vectors). 

Then, we'd only have to implement the serialize functions, which pack protobuf structures into binary strings. 

(3) As an intermediate step, we should replace the State structs with protobuf. 
```
+---------+  h265*::parse   +-------------+ protobuf +---------+
|h265 bin |---------------->|h265 protobuf|<-------->|h265 text|
+---------+                 +-------------+          +---------+
```

Other issues:
* We want the bin->text->bin conversions to be lossless. For this, we need to make sure we keep absolutely all the data. This means that, when a parser does not want to keep parsing (e.g. the slice_segment_layer just cares about the slice_segment_header, not the payload), it should keep the rest in a generic unparsed struct. This should be relatively simple.

**Comment by jhnbwrs** [comment]
Sounds like protobufs might make the project a lot more flexible.  I will consider if I want to attempt to undertake the intermediate case.  Probably won't do anything in the short term.  The use case is this particular instance is being able to iterate through the h265 nals and find the user data seis and scoop them out and move them onto a transcoded version that is using some other codec.  In the case of h264, the format is exactly the same, so being able to take the sei message and just ask it give me a byte buffer representation is handy, I can then plunk it down where it needs to be, but maybe that is just too specialized a case.  I can write something out of band to do this with the structures as they currently exist I guess.  But I do think that this could be useful.  Generally any time we might want to parse the structure and make changes to the structure (colorimetry as you mentioned being a very reasonable use case) and then write that data back out with the change while processing might be useful. I certainly wouldn't want to have to write something out to text and modify the text while processing nal data in a high performance application.

**Comment by chemag** [comment]
> Sounds like protobufs might make the project a lot more flexible. I will consider if I want to attempt to undertake the intermediate case. 

The intermediate case is anyway the next step to the full-protobuf case.

> Probably won't do anything in the short term. The use case is this particular instance is being able to iterate through the h265 nals and find the user data seis and scoop them out and move them onto a transcoded version that is using some other codec. In the case of h264, the format is exactly the same, so being able to take the sei message and just ask it give me a byte buffer representation is handy, I can then plunk it down where it needs to be, but maybe that is just too specialized a case. 

If you want to get the SEI, did you consider using the "--add-contents" option on the CLI tool?
```
$ h265nal --noas-one-line --add-contents videolan/samples/HX/A210515_130559_130613.265
...
nal_unit {
  offset: 0x000000a0
  length: 25
  nal_unit_header {
    forbidden_zero_bit: 0
    nal_unit_type: 39
    nuh_layer_id: 0
    nuh_temporal_id_plus1: 1
  }
  nal_unit_payload {
    sei message {
      payload_type: 229
      payload_size: 4unimplemented {
        payload_size: 4 
        payload { 229 229 0 0 }
      }
    }
  }
} contents { 4e 01 e5 04 e5 e5 00 00 80 48 58 56 46 e5 7a 04  00 50 51 64 07 01 00 00 00 }
...
```

Now, the "contents" field contains the full NAL unit, which includes the NAL unit header. That one is different in h264. But the bits themselves are in the contents field.


> I can write something out of band to do this with the structures as they currently exist I guess. But I do think that this could be useful. Generally any time we might want to parse the structure and make changes to the structure (colorimetry as you mentioned being a very reasonable use case) and then write that data back out with the change while processing might be useful. I certainly wouldn't want to have to write something out to text and modify the text while processing nal data in a high performance application.

Yeah, the text edit version is definitely not about performance. And in fact one could make a case that, by replacing the (current) State structs with C++ protobuf messages, performance will suffer (C++ protobuf messages are huge). So in any case I'd prefer to live a build option about whether to use one or the other.

**Comment by jhnbwrs** [comment]
Ok, I will close this for now.  Thanks for your input I probably won't do anything for now.  If I decide I want to try to convert everything to protobuf I will ping you before I start to see if you are still interested in accepting that.  I am not sure I will get around to it though.

**Comment by chemag** [comment]
> Ok, I will close this for now. Thanks for your input I probably won't do anything for now. If I decide I want to try to convert everything to protobuf I will ping you before I start to see if you are still interested in accepting that. I am not sure I will get around to it though.

Understand it. 

Thanks a lot for the SEI parser anyway!

**Pull request closed without merging**
